"""
Database Models for Project Astra
PostgreSQL + TimescaleDB schemas for trading data
"""

from datetime import datetime
from decimal import Decimal
from typing import Optional
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Boolean, Text, JSON,
    ForeignKey, Index, UniqueConstraint, Numeric
)
from sqlalchemy.dialects.postgresql import TIMESTAMP, DOUBLE_PRECISION
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
import sqlalchemy as sa

Base = declarative_base()


# =============================================================================
# MARKET DATA TABLES
# =============================================================================

class Instrument(Base):
    """Financial instruments (stocks, indices, futures, options)."""
    __tablename__ = 'instruments'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, unique=True)
    exchange = Column(String(20), nullable=False)  # NSE, BSE, NFO
    instrument_type = Column(String(20), nullable=False)  # EQUITY, INDEX, FUTURES, OPTIONS
    series = Column(String(10), default='EQ')
    lot_size = Column(Integer, default=1)
    tick_size = Column(Numeric(20, 6), default=0.05)
    strike_price = Column(Numeric(20, 2), nullable=True)
    expiry_date = Column(DateTime, nullable=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_instrument_symbol', 'symbol'),
        Index('idx_instrument_exchange', 'exchange'),
    )


class Tick(Base):
    """Raw tick data - TimescaleDB hypertable."""
    __tablename__ = 'ticks'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    exchange = Column(String(20), nullable=False)
    price = Column(Numeric(20, 4), nullable=False)
    volume = Column(BigInteger, default=0)
    bid_price = Column(Numeric(20, 4))
    ask_price = Column(Numeric(20, 4))
    bid_qty = Column(BigInteger)
    ask_qty = Column(BigInteger)
    total_buy_qty = Column(BigInteger)
    total_sell_qty = Column(BigInteger)
    timestamp = Column(TIMESTAMP(timezone=True), nullable=False, index=True)
    received_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_ticks_symbol_time', 'symbol', 'timestamp'),
    )


class Candle(Base):
    """OHLCV candle data - TimescaleDB hypertable."""
    __tablename__ = 'candles'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    exchange = Column(String(20), nullable=False)
    interval = Column(String(10), nullable=False)  # 1m, 5m, 15m, 1h, 1d
    open = Column(Numeric(20, 4), nullable=False)
    high = Column(Numeric(20, 4), nullable=False)
    low = Column(Numeric(20, 4), nullable=False)
    close = Column(Numeric(20, 4), nullable=False)
    volume = Column(BigInteger, default=0)
    oi = Column(BigInteger, default=0)  # Open interest
    timestamp = Column(TIMESTAMP(timezone=True), nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        UniqueConstraint('symbol', 'interval', 'timestamp', name='uq_candle_unique'),
        Index('idx_candle_symbol_interval_time', 'symbol', 'interval', 'timestamp'),
    )


# =============================================================================
# FEATURE ENGINEERING TABLES
# =============================================================================

class Feature(Base):
    """Calculated features for ML models."""
    __tablename__ = 'features'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    feature_name = Column(String(100), nullable=False)
    feature_value = Column(DOUBLE_PRECISION, nullable=False)
    feature_category = Column(String(50))  # technical, statistical, ml
    candle_timestamp = Column(TIMESTAMP(timezone=True), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_features_symbol_time', 'symbol', 'candle_timestamp'),
        Index('idx_features_name', 'feature_name'),
    )


# =============================================================================
# STRATEGY & SIGNAL TABLES
# =============================================================================

class StrategySignal(Base):
    """Signals generated by strategy agents."""
    __tablename__ = 'strategy_signals'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_name = Column(String(50), nullable=False, index=True)
    symbol = Column(String(50), nullable=False)
    direction = Column(String(10), nullable=False)  # LONG, SHORT
    entry_price = Column(Numeric(20, 4), nullable=False)
    stop_loss = Column(Numeric(20, 4))
    target = Column(Numeric(20, 4))
    confidence = Column(Float)
    rationale = Column(Text)
    regime = Column(String(20))  # Market regime at signal time
    status = Column(String(20), default='PENDING')  # PENDING, APPROVED, REJECTED, EXECUTED
    risk_rejection_reason = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_signal_strategy_time', 'strategy_name', 'created_at'),
    )


class TradeCandidate(Base):
    """Risk-approved trade candidates ready for execution."""
    __tablename__ = 'trade_candidates'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, ForeignKey('strategy_signals.id'))
    symbol = Column(String(50), nullable=False)
    direction = Column(String(10), nullable=False)
    entry_price = Column(Numeric(20, 4), nullable=False)
    quantity = Column(Integer, nullable=False)
    stop_loss = Column(Numeric(20, 4), nullable=False)
    target = Column(Numeric(20, 4))
    risk_amount = Column(Numeric(20, 2), nullable=False)
    expected_reward = Column(Numeric(20, 2))
    risk_reward_ratio = Column(Float)
    confidence = Column(Float)
    ml_score = Column(Float)
    ml_explanation = Column(JSON)
    status = Column(String(20), default='PENDING')
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_candidate_status', 'status'),
    )


# =============================================================================
# ORDER & TRADE TABLES
# =============================================================================

class Order(Base):
    """Orders sent to execution (paper or live)."""
    __tablename__ = 'orders'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    order_id = Column(String(50), unique=True)  # Broker order ID or internal ID
    candidate_id = Column(Integer, ForeignKey('trade_candidates.id'))
    symbol = Column(String(50), nullable=False)
    exchange = Column(String(20), nullable=False)
    side = Column(String(10), nullable=False)  # BUY, SELL
    order_type = Column(String(20), default='LIMIT')  # LIMIT, MARKET, SL, SL-M
    quantity = Column(Integer, nullable=False)
    price = Column(Numeric(20, 4))
    trigger_price = Column(Numeric(20, 4))
    product = Column(String(20), default='MIS')  # MIS, CNC, NRML
    status = Column(String(20), default='CREATED')
    # Status: CREATED, SENT, ACK, PARTIAL, FILLED, CANCELLED, REJECTED, EXITED
    filled_quantity = Column(Integer, default=0)
    average_price = Column(Numeric(20, 4))
    reject_reason = Column(Text)
    placed_at = Column(DateTime)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_order_status', 'status'),
        Index('idx_order_symbol', 'symbol'),
    )


class Fill(Base):
    """Order fills/executions."""
    __tablename__ = 'fills'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    order_id = Column(Integer, ForeignKey('orders.id'), nullable=False)
    fill_id = Column(String(50), unique=True)
    symbol = Column(String(50), nullable=False)
    side = Column(String(10), nullable=False)
    quantity = Column(Integer, nullable=False)
    price = Column(Numeric(20, 4), nullable=False)
    brokerage = Column(Numeric(20, 2), default=0)
    stt = Column(Numeric(20, 2), default=0)
    exchange_charges = Column(Numeric(20, 2), default=0)
    gst = Column(Numeric(20, 2), default=0)
    stamp_duty = Column(Numeric(20, 2), default=0)
    total_charges = Column(Numeric(20, 2), default=0)
    pnl = Column(Numeric(20, 2))
    fill_timestamp = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_fill_order', 'order_id'),
        Index('idx_fill_time', 'fill_timestamp'),
    )


class Position(Base):
    """Current open positions."""
    __tablename__ = 'positions'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, unique=True)
    exchange = Column(String(20), nullable=False)
    side = Column(String(10), nullable=False)  # LONG, SHORT
    quantity = Column(Integer, nullable=False)
    average_price = Column(Numeric(20, 4), nullable=False)
    current_price = Column(Numeric(20, 4))
    unrealized_pnl = Column(Numeric(20, 2))
    realized_pnl = Column(Numeric(20, 2), default=0)
    stop_loss = Column(Numeric(20, 4))
    target = Column(Numeric(20, 4))
    trailing_stop = Column(Numeric(20, 4))
    entry_time = Column(DateTime, nullable=False)
    exit_time = Column(DateTime)
    status = Column(String(20), default='OPEN')  # OPEN, CLOSED, PARTIAL
    exit_reason = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_position_status', 'status'),
    )


# =============================================================================
# RISK & COMPLIANCE TABLES
# =============================================================================

class RiskCheck(Base):
    """Risk check results for trades."""
    __tablename__ = 'risk_checks'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(Integer, ForeignKey('strategy_signals.id'))
    check_type = Column(String(50), nullable=False)
    check_result = Column(Boolean, nullable=False)
    reason = Column(Text)
    risk_parameters = Column(JSON)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_risk_check_signal', 'signal_id'),
    )


# =============================================================================
# REGIME & MODEL TABLES
# =============================================================================

class RegimeState(Base):
    """Market regime states."""
    __tablename__ = 'regime_states'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    regime = Column(String(20), nullable=False)  # BULL, BEAR, SIDEWAYS, HIGH_VOL, EVENT_MODE
    confidence = Column(Float, nullable=False)
    vix_level = Column(Float)
    trend_strength = Column(Float)
    volatility_level = Column(Float)
    breadth = Column(Float)
    allowed_strategies = Column(JSON)
    risk_multiplier = Column(Float, default=1.0)
    timestamp = Column(DateTime, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_regime_time', 'timestamp'),
    )


class ModelVersion(Base):
    """ML model versioning and metadata."""
    __tablename__ = 'model_versions'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    model_name = Column(String(100), nullable=False)
    version = Column(String(50), nullable=False)
    model_type = Column(String(50))  # XGBoost, LightGBM, etc.
    model_path = Column(String(255), nullable=False)
    training_date = Column(DateTime, nullable=False)
    accuracy = Column(Float)
    sharpe = Column(Float)
    max_drawdown = Column(Float)
    features_used = Column(JSON)
    is_active = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    __table_args__ = (
        UniqueConstraint('model_name', 'version', name='uq_model_version'),
    )


# =============================================================================
# ALERTS & AUDIT TABLES
# =============================================================================

class Alert(Base):
    """System alerts and notifications."""
    __tablename__ = 'alerts'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    alert_type = Column(String(50), nullable=False)
    severity = Column(String(20), default='INFO')  # INFO, WARNING, ERROR, CRITICAL
    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)
    source = Column(String(50))  # Which agent/component
    is_read = Column(Boolean, default=False)
    telegram_sent = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    __table_args__ = (
        Index('idx_alert_type_time', 'alert_type', 'created_at'),
    )


class AuditLog(Base):
    """Audit trail for all system actions."""
    __tablename__ = 'audit_logs'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    action = Column(String(100), nullable=False)
    entity_type = Column(String(50))
    entity_id = Column(Integer)
    old_values = Column(JSON)
    new_values = Column(JSON)
    user = Column(String(50), default='system')
    ip_address = Column(String(45))
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    
    __table_args__ = (
        Index('idx_audit_entity', 'entity_type', 'entity_id'),
    )
