'use client';

import React, { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
import wsClient from '@/lib/websocket';
import { Signal } from '@/lib/types';
import { Activity } from 'lucide-react';

export default function SignalFeed() {
  const { data } = useQuery({
    queryKey: ['signals'],
    queryFn: () => api.getSignals(20),
    refetchInterval: 5000,
  });

  const [signals, setSignals] = useState<Signal[]>([]);

  useEffect(() => {
    if (data?.signals) {
      setSignals(data.signals);
    }
  }, [data]);

  useEffect(() => {
    // Subscribe to websocket signal updates
    const handleWsSignal = (topic: string, updateData: any) => {
      if (topic === 'signals') {
        setSignals(prev => {
          // Add new signal at the top and cap at 20
          const exists = prev.some(s => s.id === updateData.id);
          if (!exists) {
            return [updateData, ...prev].slice(0, 20);
          }
          return prev;
        });
      }
    };

    wsClient.subscribe(['signals'], handleWsSignal);
    return () => wsClient.unsubscribe(['signals'], handleWsSignal);
  }, []);

  return (
    <div className="glass-panel p-6 rounded-xl border border-slate-900 shadow-xl space-y-4">
      <div className="flex items-center gap-2 border-b border-slate-900 pb-4">
        <Activity className="w-5 h-5 text-blue-400" />
        <div>
          <h3 className="font-bold text-white tracking-wide">Live Signal Feed</h3>
          <p className="text-xs text-slate-400">Signals generated by strategy agents</p>
        </div>
      </div>

      <div className="space-y-3 max-h-[350px] overflow-y-auto pr-1">
        {signals.length === 0 ? (
          <div className="text-center py-8 text-slate-500 text-sm">
            No signals generated yet.
          </div>
        ) : (
          signals.map((sig) => {
            const isLong = sig.direction === 'LONG';
            return (
              <div 
                key={sig.id} 
                className="bg-slate-950/50 hover:bg-slate-950 border border-slate-900/60 p-4 rounded-lg flex flex-col gap-2 transition-all duration-200"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-bold text-white">{sig.symbol}</span>
                    <span className={`px-1.5 py-0.5 rounded text-[9px] font-extrabold ${
                      isLong ? 'bg-emerald-500/10 text-emerald-400' : 'bg-rose-500/10 text-rose-400'
                    }`}>
                      {sig.direction}
                    </span>
                  </div>
                  <span className="text-[10px] text-slate-500 font-semibold uppercase">{sig.strategy.replace('_', ' ')}</span>
                </div>
                
                <div className="grid grid-cols-3 gap-2 text-xs py-1 border-y border-slate-900/30">
                  <div>
                    <span className="text-slate-500 block text-[10px] uppercase font-medium">Entry</span>
                    <span className="text-slate-200 font-semibold">₹{sig.entry_price.toFixed(2)}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[10px] uppercase font-medium">Stop Loss</span>
                    <span className="text-rose-400 font-semibold">₹{sig.stop_loss?.toFixed(2) || '—'}</span>
                  </div>
                  <div>
                    <span className="text-slate-500 block text-[10px] uppercase font-medium">Target</span>
                    <span className="text-emerald-400 font-semibold">₹{sig.target?.toFixed(2) || '—'}</span>
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="flex justify-between items-center text-[10px]">
                    <span className="text-slate-500">Confidence</span>
                    <span className="text-slate-300 font-bold">{(sig.confidence * 100).toFixed(0)}%</span>
                  </div>
                  <div className="w-full bg-slate-900 rounded-full h-1.5 overflow-hidden">
                    <div 
                      className={`h-1.5 rounded-full ${isLong ? 'bg-emerald-500 glow-green' : 'bg-rose-500 glow-red'}`} 
                      style={{ width: `${sig.confidence * 100}%` }}
                    />
                  </div>
                </div>

                <p className="text-[10px] text-slate-400 italic font-medium leading-relaxed">
                  {sig.rationale}
                </p>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
